---
- name: Ubuntu Familly - Install DSI tools
  apt:
    name: "{{ __os_common_tools_packages }}"
    state: latest
    update_cache: yes
  register: apt_res
  retries: 5
  until: apt_res is success
