---
# Loading OS correct vars
- name: Loading OS correct vars
  ansible.builtin.import_tasks: load_vars.yml
  tags:
    - load_vars

# Run tasks.
- name: Deploy common role on RHEL Familly
  ansible.builtin.import_tasks: rhel-main.yml
  when: ( ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' )
  tags:
    - os-commons-rhel

- name: Deploy common role on Debian Familly
  ansible.builtin.import_tasks: debian-main.yml
  when: (ansible_facts['os_family'] == "Debian")
  tags:
    - os-common-debian
