---
#  Tasks Execute if :
#    ansible_distribution != 'Fedora'
- name: Redhat Familly - Check if EPEL repo is already configured.
  stat:
    path: "{{ __os_common_epel_repo_path }}"
  register: epel_repofile_result

- name: Redhat Familly - Install EPEL repo GPG Key.
  rpm_key:
    state: present
    key: "{{ __os_common_epel_repo_key }}"

- name: Redhat Familly - Install EPEL repo.
  yum:
    name: "{{ __os_common_epel_repo_path }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists
