---
#  Tasks Execute if :
#    ansible_facts['distribution_major_version'] >= "8" and 
#    ansible_distribution != 'Fedora'
#
- name: "Redhat Familly - Enable powertools (dnf plugins core)"
  ansible.builtin.dnf:
    name: "dnf-plugins-core"
    state: latest
    enablerepo: "epel"

- name: Redhat Familly - Enable powertools
  community.general.ini_file:
    path: "/etc/yum.repos.d/{{ __os_common_powertools_repository_file }}"
    section: "{{ __os_common_powertools_repository_name }}"
    option: enabled
    value: "1"
    mode: "0644"
  notify:
    - Yum update cache
